version: '3.7'

services:

  public:
    build: frontend
    ports:
      - "9010:9000"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  api:
    build: backend
    ports:
      - "9011:9000"
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  console:
    build: console
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
      - backend-network

  reviewdb:
    image: postgres:${POSTGRES_MAJOR_VERSION}
    env_file:
      - .secrets
    ports:
      - "54322:5432"
    volumes:
      - ${DATA_SAVE_PATH}/postgres/${POSTGRES_MAJOR_VERSION}/data:/var/lib/postgresql/data
    networks:
      - backend-network

  sftp_test:
    image: atmoz/sftp
    volumes:
      - ./console/tests/_data:/home/testuser/editorialmanager
    expose:
      - "22"
    command: testuser:testpass:::editorialmanager
    networks:
      - backend-network

  config:
    image: rija/docker-alpine-shell-tools:1.0.1
    volumes:
      - ./:/app
    command: /app/generate_config.sh
    networks:
      - backend-network

  chrome:
    image: selenium/standalone-chrome:3.141.59-oxygen
    shm_size: '1gb' # to avoid a known issue
    ports:
      # - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access
    networks:
      backend-network:
        ipv4_address: 172.16.238.11
    environment: # to run headless, set false and comment out port 5900 above and make sure to pass --headless arg in acceptance.suite.yml
      START_XVFB: "false"

  chrome-arm:
    image: seleniarm/standalone-chromium:latest
    shm_size: '1gb' # to avoid a known issue
    ports:
      # - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access
    networks:
      backend-network:
        ipv4_address: 172.16.238.11
    extra_hosts:
      - "gigadb.test:172.16.238.10"
      - "fuw-admin-api:172.16.238.10"
    environment: # to run headless, set false and comment out port 5900 above and make sure to pass --headless arg in acceptance.suite.yml
      START_XVFB: "false"


  beanstalkd:
    build: console
    volumes:
      - ./:/app
    command: /usr/bin/beanstalkd
    ports:
      - "11300:11300"
    expose:
      - "11300"
    networks:
      - backend-network

  manuscripts-worker:
    build: console
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - reviewdb
      - beanstalkd
    command: "/usr/local/bin/php /app/yii manuscripts-q/run --verbose"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24