[google-drive]
type = drive
client_id = 30680786647-u4h25tvg120iijh4q2osh4e13v1ulg46.apps.googleusercontent.com
client_secret = hNguR2Nw_8fTYuwSU7MUialN
scope = drive
token = {"access_token":"ya29.a0ARrdaM-M_sGEzu0f6hF74Xjd4msiCqjo-obp-O-d_4ZGpstjOd0Zm7QctaMeCNKFiawct57KAnQ_AJ1CiPEt9a03QIID3UfjM-_Fk09_7CmsHg71Em9Yn410Kv3DlTDeGPKsfd5ElmwhSbn872Jouvxv_GlihQ","token_type":"Bearer","refresh_token":"1//0ecK5IKZnf0lFCgYIARAAGA4SNwF-L9IrfzmuPwx7NINysLgDgZCO6FRuwtDnddcrsv5HZHnE4tMEVU7Ufc3RifI81vpOkXW7TyA","expiry":"2021-07-07T17:13:54.525811+08:00"}

[test-cos-mac]
type = s3
provider = TencentCOS
env_auth = false
access_key_id = IKIDNbaMtCG5fz4uUpvrb6NPHuIRKyNWP4Vh
secret_access_key = ziCRQAetsc6LK4YnnX1HH4dy3uVrxoQp
endpoint = cos.ap-guangzhou.myqcloud.com
acl = default

