#Xdebug 2
zend_extension=xdebug.so

[xdebug]
xdebug.remote_host=host.docker.internal
xdebug.remote_enable=1
xdebug.coverage_enable=1
xdebug.remote_log=/tmp/xdebug.log
xdebug.remote_autostart=1
xdebug.idekey=test
; Tell Xdebug how to reach your IDE
xdebug.remote_port=9003

#XDebug3 (PHP 8 images)
#zend_extension=xdebug.so

[xdebug]
xdebug.mode=develop,debug,coverage
xdebug.client_host=host.docker.internal
xdebug.remote_log=/tmp/xdebug.log
xdebug.start_with_request=yes
xdebug.idekey=test
; Tell Xdebug how to reach your IDE
xdebug.client_port=9003